title: Michael Pimble
description: My personal website
theme: minima
author:
  name: Michael Pimble
  email: "pimblemichael@yahoo.com"

minima:
  skin: dark

header_pages:
  - about.md

collections:
  projects:
    output: true
    permalink: /projects/:path/
