title: Michael Pimble
description: My personal website
remote_theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"
author:
  name: Michael Pimble
  email: "pimblemichael@yahoo.com"

header_pages:
  - about.md

collections:
  projects:
    output: true
    permalink: /projects/:path/
